//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmongUs_ModInstaller.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsGamePathSet {
            get {
                return ((bool)(this["IsGamePathSet"]));
            }
            set {
                this["IsGamePathSet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsCPUArchitectureSet {
            get {
                return ((bool)(this["IsCPUArchitectureSet"]));
            }
            set {
                this["IsCPUArchitectureSet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsCPUArchitecture64Bit {
            get {
                return ((bool)(this["IsCPUArchitecture64Bit"]));
            }
            set {
                this["IsCPUArchitecture64Bit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("HKEY_LOCAL_MACHINE\\SOFTWARE\\Valve\\Steam")]
        public string SteamRegistryPath32Bit {
            get {
                return ((string)(this["SteamRegistryPath32Bit"]));
            }
            set {
                this["SteamRegistryPath32Bit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("HKEY_LOCAL_MACHINE\\SOFTWARE\\WOW6432Node\\Valve\\Steam")]
        public string SteamRegistryPath64Bit {
            get {
                return ((string)(this["SteamRegistryPath64Bit"]));
            }
            set {
                this["SteamRegistryPath64Bit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("InstallPath")]
        public string SteamRegistryKeyName {
            get {
                return ((string)(this["SteamRegistryKeyName"]));
            }
            set {
                this["SteamRegistryKeyName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("steamapps\\appmanifest_945360.acf")]
        public string AmongUsAppManifestSublocation {
            get {
                return ((string)(this["AmongUsAppManifestSublocation"]));
            }
            set {
                this["AmongUsAppManifestSublocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("steamapps\\libraryfolders.vdf")]
        public string SteamLibraryFoldersFileSublocation {
            get {
                return ((string)(this["SteamLibraryFoldersFileSublocation"]));
            }
            set {
                this["SteamLibraryFoldersFileSublocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AmongUsGameFullPath {
            get {
                return ((string)(this["AmongUsGameFullPath"]));
            }
            set {
                this["AmongUsGameFullPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("steamapps\\common")]
        public string SteamCommonFolderSubpath {
            get {
                return ((string)(this["SteamCommonFolderSubpath"]));
            }
            set {
                this["SteamCommonFolderSubpath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Among Us")]
        public string AmongUsGameFolderName {
            get {
                return ((string)(this["AmongUsGameFolderName"]));
            }
            set {
                this["AmongUsGameFolderName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Among Us.exe")]
        public string AmongUsGameExeName {
            get {
                return ((string)(this["AmongUsGameExeName"]));
            }
            set {
                this["AmongUsGameExeName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://raw.githubusercontent.com/NyphoX/AutomatedAmongUsModInstaller/master/publ" +
            "ic/modlist.json")]
        public string JSONModlistURL {
            get {
                return ((string)(this["JSONModlistURL"]));
            }
            set {
                this["JSONModlistURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string JSONModlist {
            get {
                return ((string)(this["JSONModlist"]));
            }
            set {
                this["JSONModlist"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Among Us (Modded by AAMI)")]
        public string AAMIModdingFolderName {
            get {
                return ((string)(this["AAMIModdingFolderName"]));
            }
            set {
                this["AAMIModdingFolderName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AAMIModdingFullPath {
            get {
                return ((string)(this["AAMIModdingFullPath"]));
            }
            set {
                this["AAMIModdingFullPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsAAMIModdingFullPathSet {
            get {
                return ((bool)(this["IsAAMIModdingFullPathSet"]));
            }
            set {
                this["IsAAMIModdingFullPathSet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ModInstallations {
            get {
                return ((string)(this["ModInstallations"]));
            }
            set {
                this["ModInstallations"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.github.com/repos/NyphoX/AutomatedAmongUsModInstaller/releases/latest")]
        public string JSONLatestAAMIRelease {
            get {
                return ((string)(this["JSONLatestAAMIRelease"]));
            }
            set {
                this["JSONLatestAAMIRelease"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AAMISettingsUpgradeRequired {
            get {
                return ((bool)(this["AAMISettingsUpgradeRequired"]));
            }
            set {
                this["AAMISettingsUpgradeRequired"] = value;
            }
        }
    }
}
